### ISSUE TITLE
download_pretrained_weights.py cannot convert downloaded models to ONNX format

### ISSUE THREAD

**Issue by hiankun** [openvinotoolkit/training_extensions#165]
**Describe the bug**

When using `tools/download_pretrained_weights.py` to download the `mask_rcnn_resnet50_fpn_2x` model, the steps of downloading and converting to `*.pth` file were successful. **The final step of converting to ONNX file was failed.**

The terminal output was as follows (similar warnings have been omitted):
```
INFO 25-10-19 14:14:48 download_pretrained_weights.py: 112] Fetching mask_rcnn_resnet50_fpn_2x (coco, detectron)
Downloading...: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 346M/346M [20:43<00:00, 291kB/s]
INFO 25-10-19 14:35:33 download_pretrained_weights.py: 122] Downloaded to /media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/data/pretrained_mod
els/raw/coco/detectron/mask_rcnn_resnet50_fpn_2x.pkl
INFO 25-10-19 14:35:33 download_pretrained_weights.py: 124] Converting weights...
WARNING 25-10-19 14:35:33 weight_converters.py: 227] Warning! No mapping for fc1000_b
WARNING 25-10-19 14:35:33 weight_converters.py: 227] Warning! No mapping for fc1000_w
INFO 25-10-19 14:35:34 download_pretrained_weights.py: 134] Converted weights file saved to /media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/d
ata/pretrained_models/converted/coco/detectron/mask_rcnn_resnet50_fpn_2x.pth
INFO 25-10-19 14:35:34 download_pretrained_weights.py: 142] Exporting to ONNX...
/media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/backbones/backbone.py:105: TracerWarning: Converting a tensor to a Python boo
lean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to oth
er inputs!
  assert output.shape[-1] * scale == src_width, '{} * {} != {}'.format(x.shape[-1], scale, src_width)
/media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/prior_box.py:52: TracerWarning: Converting a tensor to a Python integer might
 cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  torch.linspace(0, grid_w - 1, grid_w, dtype=torch.float32) * s_x + s_x * 0.5,

(similar warning omitted...)

WARNING 25-10-19 14:35:49 download_pretrained_weights.py: 171] RuntimeError('tuple appears in op that does not forward tuples, unsupported kind: prim::PythonOp (VisitNode at /pytorch/torch/csrc/jit/passes
/lower_tuples.cpp:135)\nframe #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fbcfff0f813 in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libc10.so)\nframe #1: <unknown
 function> + 0x3f39a9a (0x7fbd044a3a9a in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)\nframe #2: <unknown function> + 0x3f3b07c (0x7fbd044a507c in /home/thk/.local/lib/python3.5/si
te-packages/torch/lib/libtorch.so)\nframe #3: torch::jit::LowerAllTuples(std::shared_ptr<torch::jit::Graph>&) + 0x13 (0x7fbd044a50b3 in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)\
nframe #4: <unknown function> + 0x4ff18b (0x7fbd4b81018b in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch_python.so)\nframe #5: <unknown function> + 0x211014 (0x7fbd4b522014 in /home/thk
/.local/lib/python3.5/site-packages/torch/lib/libtorch_python.so)\n<omitting python frames>\nframe #8: python3() [0x539a13]\nframe #10: python3() [0x539a13]\nframe #12: python3() [0x539f5f]\nframe #14: py
thon3() [0x539a13]\nframe #16: python3() [0x539a13]\nframe #18: python3() [0x539a13]\nframe #21: python3() [0x539a13]\nframe #23: python3() [0x6292c2]\nframe #28: __libc_start_main + 0xf0 (0x7fbd67893830 
in /lib/x86_64-linux-gnu/libc.so.6)\n',)
```

**Steps to Reproduce**

1. Clone the repo and follow the installation guide of `Instance Segmentation in PyTorch` to complete the setup.
2. Run `tools/download_pretrained_weights.py` to download the `mask_rcnn_resnet50_fpn_2x` model.

**Environment:**
 - OS: Linux Ubuntu 16.04
 - Framework version: PyTorch 1.3.0 (via `torch.__version__`)
 - ONNX version: 1.3.0 (via `onnx.__version`)
 - Python version: 3.5.2
 - OpenVINO version: 2019 R3
 - CUDA/cuDNN version: 10.1
 - GPU model and memory: GTX 1080 8G

**Possible relevant info of converting models to ONNX**

I have successfully trained a model and test it using `tools/demo.py`. Some relevant info could be find in [#162](https://github.com/opencv/openvino_training_extensions/issues/162).

Then I tried to convert the `*.pth` file to ONNX model using the following commands:
```
python3 tools/convert_to_onnx.py \
    --model segmentoly.rcnn.model_zoo.instance_segmentation_security_0050.InstanceSegmentationSecurity0050 \
    --ckpt outputs/Oct24-11-45-33/ckpt/model_step_20000.pth \
    --input_size 800 1344 \
    --dataset coco_2017_val \
    --show_flops \
    --output_file data/pretrained_models/onnx/coco/detectron/model_step_20000.onnx
```
The conversion failed with the following error message  (similar warnings have been omitted):
```
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
/media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/utils/stats.py:179: TracerWarning: Converting a tensor to a Python integer might c
ause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  conv_module.__flops__ += int(overall_flops)
/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:90: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python v
alues, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
/media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/backbones/backbone.py:105: TracerWarning: Converting a tensor to a Python boo
lean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to oth
er inputs!
  assert output.shape[-1] * scale == src_width, '{} * {} != {}'.format(x.shape[-1], scale, src_width)
/media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/prior_box.py:52: TracerWarning: Converting a tensor to a Python integer might
 cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  torch.linspace(0, grid_w - 1, grid_w, dtype=torch.float32) * s_x + s_x * 0.5,

(similar warnings omitted...)

Traceback (most recent call last):
  File "tools/convert_to_onnx.py", line 87, in <module>
    main(args)
  File "tools/convert_to_onnx.py", line 72, in main
    printable_graph = onnx_export(net, args.input_size, args.output_file, check=args.check, verbose=args.verbose)
  File "/media/thk/storage/sandbox_2019/gitlab_proj/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/utils/onnx.py", line 66, in onnx_export
    verbose=verbose, input_names=input_names, output_names=outputs_names)
  File "/home/thk/.local/lib/python3.5/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/thk/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/thk/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/thk/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/home/thk/.local/lib/python3.5/site-packages/torch/onnx/utils.py", line 118, in _optimize_graph
    torch._C._jit_pass_lower_all_tuples(graph)
RuntimeError: tuple appears in op that does not forward tuples, unsupported kind: prim::PythonOp (VisitNode at /pytorch/torch/csrc/jit/passes/lower_tuples.cpp:135)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f6339c68813 in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x3f39a9a (0x7f62e0182a9a in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x3f3b07c (0x7f62e018407c in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #3: torch::jit::LowerAllTuples(std::shared_ptr<torch::jit::Graph>&) + 0x13 (0x7f62e01840b3 in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch.so)
frame #4: <unknown function> + 0x4ff18b (0x7f633a5ba18b in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x211014 (0x7f633a2cc014 in /home/thk/.local/lib/python3.5/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #8: python3() [0x539a13]
frame #10: python3() [0x539a13]
frame #12: python3() [0x539f5f]
frame #14: python3() [0x539a13]
frame #16: python3() [0x539a13]
frame #18: python3() [0x539a13]
frame #21: python3() [0x539a13]
frame #23: python3() [0x6292c2]
frame #28: __libc_start_main + 0xf0 (0x7f634d871830 in /lib/x86_64-linux-gnu/libc.so.6)
```

Hope the additional information helps.

**Comment by niuwenju** [comment]
up

**Comment by niuwenju** [comment]
i have solve it by changing the version of torch to 0.4.1 and torchvision==0.2.1

**Comment by Ilya-Krylov** [comment]
Segmentoly does not exist anymore, please have a look at recently added instance segmentation models https://github.com/openvinotoolkit/training_extensions#models
