### ISSUE TITLE
ImportError: No module named 'quantized_functions_cpu'

### ISSUE THREAD

**Issue by TheLostIn** [openvinotoolkit/training_extensions#202]
Hello,I was running the face_recognition on win10,here is my environment
* win10
* Anaconda 3
* pytorch                   1.2.0           py3.6_cuda92_cudnn7_1 
* openvino R3
* VS2015 with updates3
```
when I run the evaluation code ,some errors occured,I don't know what to to to solve this probleme,would you help me?
$ python evaluate_lfw.py    --val_data_root F:/DATA/lfw/    --val_list F:/project_2019/openvino/face_recognition/sphereface_pytorch/data/pairs.txt    --val_landmarks F:/project_2019/openvino/face_recognition/sphereface_pytorch/data/lfw_landmark.txt    --snap F:/project_2019/openvino/open_model_zoo/tools/downloader/public/mobilenet/Mobilenet_se_focal_121000.pt    --model mobilenet --embed_size 256
W0104 21:47:19.627739 18864 warnings.py:99] D:\EresTu\conda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py:189: UserWarning: Error checking compiler version for cl: 'utf-8' codec can't decode byte 0xd3 in position 0: invalid continuation byte
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))

Traceback (most recent call last):
  File "evaluate_lfw.py", line 30, in <module>
    from nncf.config import Config
  File "f:\project_2019\openvino\openvino_training_extensions\pytorch_toolkit\nncf\nncf\__init__.py", line 1, in <module>
    from .quantization import Quantization, SymmetricQuantizer, AsymmetricQuantizer, QuantizedNetwork, \
  File "f:\project_2019\openvino\openvino_training_extensions\pytorch_toolkit\nncf\nncf\quantization\__init__.py", line 1, in <module>
    from .algo import Quantization
  File "f:\project_2019\openvino\openvino_training_extensions\pytorch_toolkit\nncf\nncf\quantization\algo.py", line 15, in <module>
    from .layers import QUANTIZATION_MODULES, QuantizationMode, QuantizationParams, QuantizerConfig
  File "f:\project_2019\openvino\openvino_training_extensions\pytorch_toolkit\nncf\nncf\quantization\layers.py", line 24, in <module>
    from .quantize_functions import symmetric_quantize, asymmetric_quantize
  File "f:\project_2019\openvino\openvino_training_extensions\pytorch_toolkit\nncf\nncf\quantization\quantize_functions.py", line 17, in <module>
    from .extensions import QuantizedFunctionsCPU, QuantizedFunctionsCUDA
  File "f:\project_2019\openvino\openvino_training_extensions\pytorch_toolkit\nncf\nncf\quantization\extensions.py", line 31, in <module>
    verbose=False
  File "D:\EresTu\conda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 658, in load
    is_python_module)
  File "D:\EresTu\conda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 838, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\EresTu\conda3\envs\pytorch\lib\site-packages\torch\utils\cpp_extension.py", line 978, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "D:\EresTu\conda3\envs\pytorch\lib\imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'quantized_functions_cpu'
(pytorch)
```

**Comment by AlexanderDokuchaev** [comment]
Hi @TheLostIn 
Unfortunally, our target OS is Ubuntu and we have no tests on Windows.
It looks like error in [nncf](https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/nncf) module.
You can try to use previous commit [d210cffe997e2027562601ab24517ae2c0a9ac5a](https://github.com/opencv/openvino_training_extensions/tree/d210cffe997e2027562601ab24517ae2c0a9ac5a/pytorch_toolkit/face_recognition) without nncf.
