### ISSUE TITLE
Can't convert to ONNX format - "undefined symbol" error

### ISSUE THREAD

**Issue by AnthonyQuantum** [openvinotoolkit/training_extensions#240]
When I use the "example" conversion command from https://github.com/opencv/openvino_training_extensions/tree/develop/pytorch_toolkit/instance_segmentation

```sh
python3 tools/convert_to_onnx.py \
    --model segmentoly.rcnn.model_zoo.resnet_fpn_mask_rcnn.ResNet50FPNMaskRCNN \
    --ckpt data/pretrained_models/converted/coco/detectron/mask_rcnn_resnet50_fpn_2x.pth \
    --input_size 800 1344 \
    --dataset coco_2017_val \
    --show_flops \
    --output_file data/pretrained_models/onnx/coco/detectron/mask_rcnn_resnet50_fpn_2x.onnx
```

I get the following error:
```sh
Traceback (most recent call last):
  File "/usr/lib/python3.6/pydoc.py", line 347, in safeimport
    module = __import__(path)
  File "/home/avizgalov/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/resnet_fpn_mask_rcnn.py", line 19, in <module>
    from .fpn_mask_rcnn_base import FPNMaskRCNN, BboxHead, DetectionOutput, MaskHead
  File "/home/avizgalov/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/model_zoo/fpn_mask_rcnn_base.py", line 22, in <module>
    from ..detection_output import DetectionOutput
  File "/home/avizgalov/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/detection_output.py", line 23, in <module>
    from .nms_function import nms
  File "/home/avizgalov/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/rcnn/nms_function.py", line 19, in <module>
    from ..extensions._EXTRA import nms as nms_impl
ImportError: /home/avizgalov/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/extensions/_EXTRA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z36deform_conv_backward_parameters_cudaRN2at6TensorES1_S1_S1_S1_S1_iiiiiiiiif

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/convert_to_onnx.py", line 87, in <module>
    main(args)
  File "tools/convert_to_onnx.py", line 64, in main
    net = locate(args.model)(classes_num, fc_detection_head=False)
  File "/usr/lib/python3.6/pydoc.py", line 1586, in locate
    nextmodule = safeimport('.'.join(parts[:n+1]), forceload)
  File "/usr/lib/python3.6/pydoc.py", line 362, in safeimport
    raise ErrorDuringImport(path, sys.exc_info())
pydoc.ErrorDuringImport: problem in segmentoly.rcnn.model_zoo.resnet_fpn_mask_rcnn - ImportError: /home/avizgalov/openvino_training_extensions/pytorch_toolkit/instance_segmentation/segmentoly/extensions/_EXTRA.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _Z36deform_conv_backward_parameters_cudaRN2at6TensorES1_S1_S1_S1_S1_iiiiiiiiif
```

Could you, please, tell me how to solve this problem?

- Linux Ubuntu 18.04
- torch 0.4.1
- python 3.6
- openvino_2020.1.053

**Comment by niuwenju** [comment]
torch 0.4.1 not support CPU,please use GPU with CUDA9.0+cudnn7.5 may be solve it.
