### ISSUE TITLE
Fault in ../../external/mmdetection/tools/dist_train.sh configs/person_vehicle_bike_sd512_mb2_clustered.py 1

### ISSUE THREAD

**Issue by vtimofeev01** [openvinotoolkit/training_extensions#260]
After making and starting venv i tried to:
../../external/mmdetection/tools/dist_train.sh configs/person_vehicle_bike_sd512_mb2_clustered.py 1
but it raises:
 ../../external/mmdetection/tools/dist_train.sh configs/person_vehicle_bike_sd512_mb2_clustered.py 1
2020-03-27 03:32:33,793 - INFO - Distributed training: True
2020-03-27 03:32:36,152 - INFO - load checkpoint from ./checkpoint/person_vehicle_bike_sd512_mb2_clustered_epoch_21.pth
2020-03-27 03:32:36,180 - WARNING - unexpected key in source state_dict: backbone.extra_convs.4.0.weight, backbone.extra_convs.4.1.weight, backbone.extra_convs.4.1.bias, backbone.extra_convs.4.1.running_mean, backbone.extra_convs.4.1.running_var, backbone.extra_convs.4.1.num_batches_tracked, backbone.extra_convs.5.0.weight, backbone.extra_convs.5.1.weight, backbone.extra_convs.5.1.bias, backbone.extra_convs.5.1.running_mean, backbone.extra_convs.5.1.running_var, backbone.extra_convs.5.1.num_batches_tracked, backbone.extra_convs.6.0.weight, backbone.extra_convs.6.1.weight, backbone.extra_convs.6.1.bias, backbone.extra_convs.6.1.running_mean, backbone.extra_convs.6.1.running_var, backbone.extra_convs.6.1.num_batches_tracked, backbone.extra_convs.7.0.weight, backbone.extra_convs.7.1.weight, backbone.extra_convs.7.1.bias, backbone.extra_convs.7.1.running_mean, backbone.extra_convs.7.1.running_var, backbone.extra_convs.7.1.num_batches_tracked, backbone.extra_convs.8.0.weight, backbone.extra_convs.8.1.weight, backbone.extra_convs.8.1.bias, backbone.extra_convs.8.1.running_mean, backbone.extra_convs.8.1.running_var, backbone.extra_convs.8.1.num_batches_tracked, backbone.extra_convs.9.0.weight, backbone.extra_convs.9.1.weight, backbone.extra_convs.9.1.bias, backbone.extra_convs.9.1.running_mean, backbone.extra_convs.9.1.running_var, backbone.extra_convs.9.1.num_batches_tracked, backbone.extra_convs.10.0.weight, backbone.extra_convs.10.1.weight, backbone.extra_convs.10.1.bias, backbone.extra_convs.10.1.running_mean, backbone.extra_convs.10.1.running_var, backbone.extra_convs.10.1.num_batches_tracked, backbone.extra_convs.11.0.weight, backbone.extra_convs.11.1.weight, backbone.extra_convs.11.1.bias, backbone.extra_convs.11.1.running_mean, backbone.extra_convs.11.1.running_var, backbone.extra_convs.11.1.num_batches_tracked, backbone.extra_convs.12.0.weight, backbone.extra_convs.12.1.weight, backbone.extra_convs.12.1.bias, backbone.extra_convs.12.1.running_mean, backbone.extra_convs.12.1.running_var, backbone.extra_convs.12.1.num_batches_tracked, bbox_head.loss_balancer.weight

missing keys in source state_dict: bbox_head.loss_weights

2020-03-27 03:32:36,181 - INFO - Start running, host: imt@imt-G7-7790, work_dir: /home/imt/openvino_training_extensions/pytorch_toolkit/object_detection/models/person_vehicle_bike_sd512_mb2_clustered
2020-03-27 03:32:36,181 - INFO - workflow: [('train', 1)], max: 5 epochs
Traceback (most recent call last):
  File "../../external/mmdetection/tools/train.py", line 98, in <module>
    main()
  File "../../external/mmdetection/tools/train.py", line 94, in main
    logger=logger)

as I manually try:
python
>>> import torch
>>> torch.backends.cudnn.enabled
True

Please tell me what to do

**Steps to Reproduce**

1.bash init_venv.sh
2.. venv/bin/activate
3. ../../external/mmdetection/tools/dist_train.sh configs/person_vehicle_bike_sd512_mb2_clustered.py 1

4.oups.....

**Environment:**
 - OS:Linux Ubuntu 18.04
 - Framework version: PyTorch last
 - Python version:3.6
 - OpenVINO version: last
 - CUDA/cuDNN version: last
 - GPU model and memory: RTX2060

**Comment by Ilya-Krylov** [comment]
Training, export, evaluation code for pytorch models are verified now. Model that you mention has been removed and replaced by better ones. Please see https://github.com/openvinotoolkit/training_extensions#models
