### ISSUE TITLE
text detector training with different size image 

### ISSUE THREAD

**Issue by rawat123** [openvinotoolkit/training_extensions#326]
Hi,

i am trying to train text detection https://github.com/opencv/openvino_training_extensions/tree/develop/tensorflow_toolkit/text_detectio...  and default it is set for image size 1280*768 , but i want to train  it on cropped vehicle number plate, i have resized my images to 200*120px size   

 

is there any doc available to understand config.yaml, 

some fields there are like 

min_area: 300

score_map_shape: [128,128]

train_image_shape : [512,512] 

i tried setting train_image_shpae to 200,120 but train.py throws error.
 

can someone please explain these. 

 

Thanks & Regards

A Rawat

**Comment by buuvo95** [comment]
I met the problem too, when I change the size of train_image_shape: [1920,1920], i have the error. Seem like the model is wrote for [512, 512] input shape.
@Ilya-Krylov can I train this model with another size.?

**Comment by Ilya-Krylov** [comment]
I would be better if you provide error log. If train_image_shape is [x,y] than score_map_shape is [x/4,y/4].

If you looking for text detector where text is represented by axis-aligned rectangular bounding boxes I would recommend to use https://github.com/openvinotoolkit/training_extensions/blob/develop/pytorch_toolkit/object_detection/model_templates/horizontal-text-detection/readme.md

**Comment by buuvo95** [comment]
When I change train_image_shape to [1280,1280] and score_map_shape to [320,320]. I got this error.
`Traceback (most recent call last):
  File "tools/train.py", line 237, in <module>
    main()
  File "tools/train.py", line 233, in main
    train(args, config)
  File "tools/train.py", line 159, in train
    model.load_weights(args.weights)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/keras/engine/training.py", line 162, in load_weights
    return super(Model, self).load_weights(filepath, by_name)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/keras/engine/network.py", line 1387, in load_weights
    status = self._trackable_saver.restore(filepath)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/tracking/util.py", line 1221, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/tracking/base.py", line 210, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/tracking/base.py", line 867, in _restore_from_checkpoint_position
    visit_queue=visit_queue)))
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/tracking/base.py", line 879, in _single_restoration_from_checkpoint_position
    restore_ops = checkpoint_position.restore_ops()
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/tracking/base.py", line 396, in restore_ops
    self._checkpoint.restore_saveables(tensor_saveables, python_saveables))
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/tracking/util.py", line 223, in restore_saveables
    validated_saveables).restore(self.save_path_tensor)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/saving/functional_saver.py", line 255, in restore
    restore_ops.update(saver.restore(file_prefix))
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/saving/functional_saver.py", line 102, in restore
    restored_tensors, restored_shapes=None)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 114, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 286, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/home/richard/.conda/envs/pixel_link_openvino/lib/python3.5/site-packages/tensorflow/python/framework/tensor_shape.py", line 1110, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (1, 1, 320, 1280) and (1, 1, 1792, 2) are incompatible
`
How can I train my custom data with another size that different from [512,512].
Btw, thank you for you recommend, I will try the horizontal-text-detection.
