### ISSUE TITLE
CUDA + mmdetection = Error

### ISSUE THREAD

**Issue by raymondlo84** [openvinotoolkit/training_extensions#481]
I believe we are missing a step (i.e., the pre-req for CUDA), as I'm getting this in the init_venv.sh step. @Ilya-Krylov ? on Ubuntu 18.04 with RTX 2060 mobile graphics card. 

`Obtaining file:///home/raymondlo84/Documents/training_extensions/external/mmdetection
    ERROR: Command errored out with exit status 1:
     command: /home/raymondlo84/Documents/training_extensions/models/text_spotting/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/raymondlo84/Documents/training_extensions/external/mmdetection/setup.py'"'"'; __file__='"'"'/home/raymondlo84/Documents/training_extensions/external/mmdetection/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ozcnvh3m
         cwd: /home/raymondlo84/Documents/training_extensions/external/mmdetection/
    Complete output (13 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/raymondlo84/Documents/training_extensions/external/mmdetection/setup.py", line 229, in <module>
        sources=['src/compiling_info.cpp']),
      File "/home/raymondlo84/Documents/training_extensions/external/mmdetection/setup.py", line 111, in make_cuda_ext
        extra_compile_args=extra_compile_args)
      File "/home/raymondlo84/Documents/training_extensions/models/text_spotting/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 728, in CUDAExtension
        library_dirs += library_paths(cuda=True)
      File "/home/raymondlo84/Documents/training_extensions/models/text_spotting/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 818, in library_paths
        if (not os.path.exists(_join_cuda_home(lib_dir)) and
      File "/home/raymondlo84/Documents/training_extensions/models/text_spotting/venv/lib/python3.6/site-packages/torch/utils/cpp_extension.py", line 1676, in _join_cuda_home
        raise EnvironmentError('CUDA_HOME environment variable is not set. '
    OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
    ----------------------------------------
WARNING: Discarding file:///home/raymondlo84/Documents/training_extensions/external/mmdetection. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by Ilya-Krylov** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/482

**Comment by Ilya-Krylov** [comment]
https://github.com/openvinotoolkit/training_extensions/pull/485
