### ISSUE TITLE
ModuleNotFoundError: No module named 'mmcv._ext'

### ISSUE THREAD

**Issue by FenixFly** [openvinotoolkit/training_extensions#572]
Hello all!

I am trying to train object detection model, I use your instruction: https://github.com/openvinotoolkit/training_extensions/tree/develop/models/object_detection

But it shows me that error ModuleNotFoundError: No module named 'mmcv._ext'

Traceback:
```
INFO:root:Commandline:
train.py --load-weights /tmp/my_model/snapshot.pth --train-ann-files /home/eugene/Desktop/popit/training_extensions/models/object_detection/../../data/popit-dataset/train.json --train-data-roots /home/eugene/Desktop/popit/training_extensions/models/object_detection/../../data/popit-dataset/train --val-ann-files /home/eugene/Desktop/popit/training_extensions/models/object_detection/../../data/popit-dataset/val.json --val-data-roots /home/eugene/Desktop/popit/training_extensions/models/object_detection/../../data/popit-dataset/val --save-checkpoints-to /tmp/my_model/outputs --classes popit,pressed,released --gpu-num 0
INFO:root:Training started ...
INFO:root:Training on CPU started ...
Traceback (most recent call last):
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/tools/train.py", line 22, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .fake_input import get_fake_input
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/apis/fake_input.py", line 20, in <module>
    from mmdet.datasets.pipelines import Compose
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/datasets/__init__.py", line 1, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/datasets/builder.py", line 26, in <module>
    from .dataset_wrappers import ConcatDataset, RepeatDataset
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/datasets/dataset_wrappers.py", line 10, in <module>
    from .coco import CocoDataset
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/datasets/coco.py", line 18, in <module>
    from mmdet.core import eval_recalls
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/core/anchor/__init__.py", line 1, in <module>
    from .anchor_generator import (AnchorGenerator, LegacyAnchorGenerator,
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/core/anchor/anchor_generator.py", line 7, in <module>
    from mmdet.core.utils.misc import meshgrid
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/core/utils/__init__.py", line 3, in <module>
    from .misc import mask2ndarray, multi_apply, unmap
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/core/utils/misc.py", line 9, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/core/mask/structures.py", line 8, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
INFO:root:... training on CPU completed.
INFO:root:... training completed.
```

list of installed packages after init_venv
```
Package                 Version      Location
----------------------- ------------ -------------------------------------------------------------------
absl-py                 0.13.0
addict                  2.4.0
albumentations          0.4.6
appdirs                 1.4.4
astroid                 2.5.8
asynctest               0.13.0
attrs                   21.2.0
cachetools              4.2.2
certifi                 2021.5.30
chardet                 4.0.0
cityscapesScripts       2.2.0
click                   8.0.1
codecov                 2.1.11
colorama                0.4.4
coloredlogs             15.0.1
coverage                5.5
cycler                  0.10.0
Cython                  0.29.23
editdistance            0.5.3
flake8                  3.9.2
flatbuffers             2.0
google-auth             1.32.1
google-auth-oauthlib    0.4.4
graphviz                0.16
grpcio                  1.38.1
humanfriendly           9.2
idna                    2.10
imagecorruptions        1.1.2
imageio                 2.9.0
imagesize               1.2.0
imgaug                  0.4.0
importlib-metadata      4.6.1
iniconfig               1.1.1
interrogate             1.4.0
isort                   4.3.21
joblib                  1.0.1
jsonschema              3.2.0
jstyleson               0.0.2
kiwisolver              1.3.1
kwarray                 0.5.19
lazy-object-proxy       1.6.0
lxml                    4.6.3
Markdown                3.3.4
matplotlib              3.4.2
mccabe                  0.6.1
mmcv-full               1.3.0
mmdet                   2.9.0        /home/eugene/Desktop/popit/training_extensions/external/mmdetection
mmlvis                  10.5.3
mmpycocotools           12.0.3
natsort                 7.1.1
networkx                2.6.1
ninja                   1.10.0.post2
nncf                    1.7.0
numpy                   1.21.0
oauthlib                3.1.1
onnx                    1.9.0
onnxoptimizer           0.2.6
onnxruntime             1.8.1
opencv-python           4.5.2.54
ordered-set             4.0.2
ote                     0.2          /home/eugene/Desktop/popit/training_extensions/ote
packaging               21.0
pandas                  1.3.0
Pillow                  8.3.1
pip                     21.1.3
pkg-resources           0.0.0
pluggy                  0.13.1
Polygon3                3.0.8
protobuf                3.17.3
py                      1.10.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycodestyle             2.7.0
pydot                   1.4.2
pyflakes                2.3.1
pylint                  2.7.2
pyparsing               2.4.7
pyquaternion            0.9.9
pyrsistent              0.18.0
pytest                  6.2.4
python-dateutil         2.8.1
pytorchcv               0.0.55
pytz                    2021.1
PyWavelets              1.1.1
PyYAML                  5.3.1
requests                2.25.1
requests-oauthlib       1.3.0
rsa                     4.7.2
scikit-image            0.18.2
scikit-learn            0.24.2
scipy                   1.7.0
setuptools              57.1.0
Shapely                 1.7.1
six                     1.16.0
sklearn                 0.0
sty                     1.0.0b12
tabulate                0.8.9
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
terminaltables          3.1.0
texttable               1.6.3
threadpoolctl           2.1.0
tifffile                2021.7.2
toml                    0.10.2
torch                   1.8.1
torchvision             0.9.1
tqdm                    4.61.2
typed-ast               1.4.3
typing                  3.7.4.3
typing-extensions       3.10.0.0
ubelt                   0.9.5
urllib3                 1.26.6
Werkzeug                2.0.1
wheel                   0.36.2
wrapt                   1.12.1
xdoctest                0.15.5
yapf                    0.31.0
zipp                    3.5.0
```
Ubuntu 18.04.5

**Comment by druzhkov-paul** [comment]
@FenixFly Do you have GPUs and CUDA on your machine? Could you please also run `python external/mmdetection/mmdet/utils/collect_env.py` and share the output?

**Comment by FenixFly** [comment]
@druzhkov-paul collect_env.py doesn't work because of error "ModuleNotFoundError: No module named 'mmcv._ext'" too:
```
(detection)(base) eugene@black-pc-eugene:~/Desktop/popit/training_extensions$ python /home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/utils/collect_env.py 
Traceback (most recent call last):
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/utils/collect_env.py", line 43, in <module>
    for name, val in collect_env().items():
  File "/home/eugene/Desktop/popit/training_extensions/external/mmdetection/mmdet/utils/collect_env.py", line 13, in collect_env
    from mmcv.ops import get_compiler_version, get_compiling_cuda_version
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/eugene/Desktop/popit/training_extensions/models/object_detection/venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
```

**Comment by druzhkov-paul** [comment]
Ok, what about CUDA and GPUs?

**Comment by FenixFly** [comment]
> 
> 
> Ok, what about CUDA and GPUs?

GXT1070Ti, Cuda 11.0

Training launched on CPU (from logs)

**Comment by druzhkov-paul** [comment]
I may suggest trying to downgrading CUDA to 10.2 or upgrade the version of mmcv-full (you may find [this PR](https://github.com/openvinotoolkit/mmdetection/pull/130) sufficient).

We'll validate multiple versions to get better setup, but it'll take some time.

**Comment by FenixFly** [comment]
@druzhkov-paul 
Yes, it works using CUDA 10.2, thank you!
