### ISSUE TITLE
Fresh install - fails to train on example dataset

### ISSUE THREAD

**Issue by WingRS** [openvinotoolkit/training_extensions#588]
Hi, I just followed the steps for the training custom object detect mobilenet model and the train.py failed to run due to a dependency issue: 
```
  File "/home/user/training_extensions/external/mmdetection/tools/train.py", line 22, in <module>
    from mmdet.apis import set_random_seed, train_detector
  File "/home/user/training_extensions/external/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .fake_input import get_fake_input
  File "/home/user/training_extensions/external/mmdetection/mmdet/apis/fake_input.py", line 20, in <module>
    from mmdet.datasets.pipelines import Compose
  File "/home/user/training_extensions/external/mmdetection/mmdet/datasets/__init__.py", line 1, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "/home/user/training_extensions/external/mmdetection/mmdet/datasets/builder.py", line 26, in <module>
    from .dataset_wrappers import ConcatDataset, RepeatDataset
  File "/home/user/training_extensions/external/mmdetection/mmdet/datasets/dataset_wrappers.py", line 10, in <module>
    from .coco import CocoDataset
  File "/home/user/training_extensions/external/mmdetection/mmdet/datasets/coco.py", line 18, in <module>
    from mmdet.core import eval_recalls
  File "/home/user/training_extensions/external/mmdetection/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/home/user/training_extensions/external/mmdetection/mmdet/core/anchor/__init__.py", line 1, in <module>
    from .anchor_generator import (AnchorGenerator, LegacyAnchorGenerator,
  File "/home/user/training_extensions/external/mmdetection/mmdet/core/anchor/anchor_generator.py", line 7, in <module>
    from mmdet.core.utils.misc import meshgrid
  File "/home/user/training_extensions/external/mmdetection/mmdet/core/utils/__init__.py", line 3, in <module>
    from .misc import mask2ndarray, multi_apply, unmap
  File "/home/user/training_extensions/external/mmdetection/mmdet/core/utils/misc.py", line 9, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/home/user/training_extensions/external/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/home/user/training_extensions/external/mmdetection/mmdet/core/mask/structures.py", line 8, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/home/user/training_extensions/models/object_detection/venv/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/user/training_extensions/models/object_detection/venv/lib/python3.8/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/user/training_extensions/models/object_detection/venv/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Killing subprocess 45926
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/training_extensions/models/object_detection/venv/lib/python3.8/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/user/training_extensions/models/object_detection/venv/lib/python3.8/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/user/training_extensions/models/object_detection/venv/lib/python3.8/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/training_extensions/models/object_detection/venv/bin/python', '-u', '/home/user/training_extensions/external/mmdetection/tools/train.py', '--local_rank=0', 'model.py', '--launcher', 'pytorch', '--update_config', 'data.train.dataset.ann_file=/home/user/training_extensions/models/object_detection/../../data/airport/annotation_example_train.json', 'data.train.dataset.img_prefix=/home/user/training_extensions/models/object_detection/../../data/airport/train', 'data.val.ann_file=/home/user/training_extensions/models/object_detection/../../data/airport/annotation_example_val.json', 'data.val.img_prefix=/home/user/training_extensions/models/object_detection/../../data/airport/val', 'work_dir=/tmp/my_model/outputs', 'data.samples_per_gpu=64', 'resume_from=', 'load_from=/tmp/my_model/snapshot.pth', 'optimizer.lr=0.05', 'total_epochs=15', 'data.train.dataset.classes=["vehicle","person","non-vehicle"]', 'data.val.classes=["vehicle","person","non-vehicle"]', 'data.test.classes=["vehicle","person","non-vehicle"]', 'model.bbox_head.num_classes=3']' returned non-zero exit status 1.
INFO:root:... training on GPUs completed.
INFO:root:... training completed.

```

**Comment by WingRS** [comment]
Fixed by adding ```--force-reinstall``` tag to init_venv.sh

**Comment by vinaykumarhs2020** [comment]
Hey @WingRS - What procedure did you follow to set number of classes? Following last `train.py` option as `--classes ${CLASSES}` from [readme](https://github.com/openvinotoolkit/training_extensions/blob/develop/models/instance_segmentation/model_templates/custom-instance-segmentation/readme.md)  throws me error:
```
train.py: error: unrecognized arguments: --classes ....
```
