### ISSUE TITLE
mmvc version issue

### ISSUE THREAD

**Issue by franva** [openvinotoolkit/training_extensions#596]
**Describe the bug**

**Steps to Reproduce**

Followed the instruction step by step and when run
`python export.py    --load-weights ${SNAPSHOT}    --save-model-to export`

It errors out:

```
$ python export.py    --load-weights ${SNAPSHOT}    --save-model-to export

out_obj <ote.modules.arg_parsers.default.DefaultArgParser object at 0x7f0614b9ea60>
obj_type InstanceSegmentationExporter
out_obj <ote.modules.exporters.instance_segmentation.InstanceSegmentationExporter object at 0x7f0614b9e520>
Traceback (most recent call last):
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/tools/export.py", line 27, in <module>
    from mmdet.apis import get_fake_input, init_detector
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/__init__.py", line 23, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.3.9 is used but incompatible. Please install mmcv>=1.2.4, <=1.3.0.
Traceback (most recent call last):
  File "export.py", line 41, in <module>
    main()
  File "export.py", line 37, in main
    exporter(ote_args)
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/ote/ote/modules/exporters/base.py", line 31, in __call__
    self._export_to_openvino(args, tools_dir)
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/ote/ote/modules/exporters/instance_segmentation.py", line 33, in _export_to_openvino
    run(f'python3 {os.path.join(tools_dir, "export.py")} '
  File "/home/winstonfan/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/tools/export.py model.py snapshot.pth export --opset=11 openvino --input_format BGR --input_shape 480 480' returned non-zero exit status 1.
```

I saw it asks for older version of `mmcv`, so I uninstalled the 1.3.9 and installed 1.3.0 as required by
`pip install mmcv==1.3.0` under the venv `instance_segmentation`, then run the command again, got another error:

```
$ python export.py    --load-weights ${SNAPSHOT}    --save-model-to export

out_obj <ote.modules.arg_parsers.default.DefaultArgParser object at 0x7fb127222a60>
obj_type InstanceSegmentationExporter
out_obj <ote.modules.exporters.instance_segmentation.InstanceSegmentationExporter object at 0x7fb127222af0>
Traceback (most recent call last):
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/tools/export.py", line 27, in <module>
    from mmdet.apis import get_fake_input, init_detector
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/apis/__init__.py", line 1, in <module>
    from .fake_input import get_fake_input
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/apis/fake_input.py", line 20, in <module>
    from mmdet.datasets.pipelines import Compose
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/datasets/__init__.py", line 1, in <module>
    from .builder import DATASETS, PIPELINES, build_dataloader, build_dataset
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/datasets/builder.py", line 26, in <module>
    from .dataset_wrappers import ConcatDataset, RepeatDataset
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/datasets/dataset_wrappers.py", line 10, in <module>
    from .coco import CocoDataset
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/datasets/coco.py", line 18, in <module>
    from mmdet.core import eval_recalls
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/core/__init__.py", line 1, in <module>
    from .anchor import *  # noqa: F401, F403
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/core/anchor/__init__.py", line 1, in <module>
    from .anchor_generator import (AnchorGenerator, LegacyAnchorGenerator,
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/core/anchor/anchor_generator.py", line 7, in <module>
    from mmdet.core.utils.misc import meshgrid
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/core/utils/__init__.py", line 3, in <module>
    from .misc import mask2ndarray, multi_apply, unmap
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/core/utils/misc.py", line 9, in <module>
    from ..mask.structures import BitmapMasks, PolygonMasks
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/core/mask/__init__.py", line 2, in <module>
    from .structures import BaseInstanceMasks, BitmapMasks, PolygonMasks
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/mmdet/core/mask/structures.py", line 8, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/models/instance_segmentation/venv/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/models/instance_segmentation/venv/lib/python3.8/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/models/instance_segmentation/venv/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/winstonfan/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'
Traceback (most recent call last):
  File "export.py", line 41, in <module>
    main()
  File "export.py", line 37, in main
    exporter(ote_args)
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/ote/ote/modules/exporters/base.py", line 31, in __call__
    self._export_to_openvino(args, tools_dir)
  File "/media/winstonfan/Workspace/Learning/Github/training_extensions/ote/ote/modules/exporters/instance_segmentation.py", line 33, in _export_to_openvino
    run(f'python3 {os.path.join(tools_dir, "export.py")} '
  File "/home/winstonfan/anaconda3/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /media/winstonfan/Workspace/Learning/Github/training_extensions/external/mmdetection/tools/export.py model.py snapshot.pth export --opset=11 openvino --input_format BGR --input_shape 480 480' returned non-zero exit status 1.
```
I have checked the `venv` lib and I can confirm that I do not have the mmcv_full installed
![image](https://user-images.githubusercontent.com/5151146/129872676-7f334940-d8e4-41a6-a006-b28617275e58.png)

Please help.

**Environment:**
 - OS:  Ubuntu 20.04
 - Framework version:  PyTorch
 - Python version: 3.8.3
 - OpenVINO version: I didn't install it, I guess it is installed by running ./init_venv.sh
 - CUDA/cuDNN version: 11.2
 - GPU model and memory: NVIDIA 2080 Ti 11GB RAM

**Comment by pkcktkksh98** [comment]
From my experience, I install `pip install mmcv==1.3.0` and `pip install mmcv_full==<version_needed>` . And it sorts of solve the problem

**Comment by druzhkov-paul** [comment]
@franva Which model is this and what instruction have you followed for setting things up?

`mmcv-full` 1.3.0 should be installed by [init_venv.sh](https://github.com/openvinotoolkit/training_extensions/blob/develop/models/instance_segmentation/init_venv.sh#L74) script. Please make sure, that you run it and activated corresponding virtual environment after.

If you configured virtual environment manually, please make sure, that you have `mmcv-full` installed (version 1.3.0 built for correct PyTorch and CUDA versions), but not `mmcv`.
