### ISSUE TITLE
Error in converting PyTorch model to ONNX 

### ISSUE THREAD

**Issue by VernicaJ** [openvinotoolkit/training_extensions#602]
Hello, I am running into this error while trying to convert Pytorch model to ONNX format.

```
To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor'). (Triggered internally at  /opt/conda/conda-bld/pytorch_1623448224956/work/aten/src/ATen/native/BinaryOps.cpp:467.)
  return torch.floor_divide(self, other)
Traceback (most recent call last):
  File "../../../../external/deep-object-reid/tools/convert_to_onnx.py", line 160, in <module>
    main()
  File "../../../../external/deep-object-reid/tools/convert_to_onnx.py", line 148, in main
    operator_export_type=torch.onnx.OperatorExportTypes.ONNX
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/__init__.py", line 280, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/utils.py", line 94, in export
    use_external_data_format=use_external_data_format)
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/utils.py", line 695, in _export
    dynamic_axes=dynamic_axes)
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/utils.py", line 467, in _model_to_graph
    module=module)
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/utils.py", line 200, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/__init__.py", line 313, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/utils.py", line 994, in _run_symbolic_function
    return symbolic_fn(g, *inputs, **attrs)
  File "/home/vernica_nb02/anaconda3/envs/reid/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 172, in wrapper
    return fn(g, *args, **kwargs)
  File "/home/vernica_nb02/training_extensions/external/deep-object-reid/scripts/script_utils.py", line 109, in group_norm_symbolic
    channels_num = input_blob.type().sizes()[1]
TypeError: 'NoneType' object is not subscriptable 
(Occurred when translating group_norm).

```
I have followed all the steps in README. This is the command I am using for convertion:

`python ../../../../external/deep-object-reid/tools/convert_to_onnx.py --config /home/vernica_nb02/training_extensions/misc/pytorch_toolkit/object_reidentification/person_reidentification/configs/person-reidentification-retail-0265.yaml --output-name PersonREID_Test.onnx model.load_weights /home/vernica_nb02/training_extensions/misc/pytorch_toolkit/object_reidentification/person_reidentification/outputs_old/reid-0265/model/model.pth.tar-5`

Could you please advice on a solution. Thank you.

**Comment by sovrasov** [comment]
Support of the reid component has been discontinued.
The most stable repository state for training and export of reid models is https://github.com/openvinotoolkit/training_extensions/tree/789896de22a2c99753c31c2659ee542b2cc8588e/pytorch_toolkit/object_reidentification
