### ISSUE TITLE
get big bug when training pedestriandb_twinnet_actionnet with sixe classes

### ISSUE THREAD

**Issue by songsonggithub** [openvinotoolkit/training_extensions#643]
**Describe the bug**

**Steps to Reproduce**

1. running tools/train.py
2. comming the bug (see me luck)
3.
4.

**Environment:**
 - OS:  ubuntu 16.04
 - Framework version: tensorflow1.12
 - Python version:2.7 or 3.6
 - OpenVINO version:latest
 - CUDA/cuDNN version:11.1
 - GPU model and memory:11g(2080ti)

-------------------------------------------------      my log detail     ---------------------------------------------------------
2021-10-21 09:22:19.322726: 0: Train loss: 6.662 Time: 78.691 s/iter
2021-10-21 09:24:13.938017: 100: Train loss: 5.390 Time: 1.146 s/iter
2021-10-21 09:24:56.759900: 200: Train loss: 4.917 Time: 0.428 s/iter
2021-10-21 09:25:40.137240: 300: Train loss: 4.327 Time: 0.434 s/iter
2021-10-21 09:26:23.592871: 400: Train loss: 3.987 Time: 0.435 s/iter
2021-10-21 09:27:07.051277: 500: Train loss: 3.762 Time: 0.435 s/iter
2021-10-21 09:27:50.211362: 600: Train loss: 3.601 Time: 0.432 s/iter
2021-10-21 09:28:32.706944: 700: Train loss: 3.828 Time: 0.425 s/iter
2021-10-21 09:29:15.538427: 800: Train loss: 3.699 Time: 0.428 s/iter
2021-10-21 09:29:58.428954: 900: Train loss: 4.037 Time: 0.429 s/iter
2021-10-21 09:30:40.825944: 1000: Train loss: 4.057 Time: 0.424 s/iter
2021-10-21 09:31:27.971951: 1100: Train loss: 3.428 Time: 0.471 s/iter
2021-10-21 09:32:09.952517: 1200: Train loss: 3.904 Time: 0.420 s/iter
2021-10-21 09:32:51.920058: 1300: Train loss: 3.785 Time: 0.420 s/iter
2021-10-21 09:33:34.321939: 1400: Train loss: 3.018 Time: 0.424 s/iter
Traceback (most recent call last):
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/tools/models/train.py", line 77, in <module>
    main()
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/tools/models/train.py", line 73, in main
    task_monitor.train(args.train_data)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/monitors/base_monitor.py", line 442, in train
    self._optimize(sess, global_step, train_op, loss_op, summary_op, is_training)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/monitors/base_monitor.py", line 408, in _optimize
    _ = sess.run(train_op, feed_dict={is_training: True})
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input must have at least k columns. Had 3, needed 5
	 [[node tower_0/ActionNet_losses/multibox_loss/det_top/cond/TopKV2 (defined at /home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/ssd.py:271)  = TopKV2[T=DT_FLOAT, sorted=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_0/ActionNet_losses/multibox_loss/det_top_1/cond/Reshape, tower_0/ActionNet_losses/multibox_loss/det_top/cond/Maximum)]]
	 [[{{node tower_0/ActionNet_losses/multibox_loss/det_top/cond/ones/_4231}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5426_tower_0/ActionNet_losses/multibox_loss/det_top/cond/ones", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'tower_0/ActionNet_losses/multibox_loss/det_top/cond/TopKV2', defined at:
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/tools/models/train.py", line 77, in <module>
    main()
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/tools/models/train.py", line 73, in main
    task_monitor.train(args.train_data)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/monitors/base_monitor.py", line 433, in train
    train_op, loss_op, towers = self._multi_gpu_training(global_step, is_training, data_iterator)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/monitors/base_monitor.py", line 317, in _multi_gpu_training
    tower = self._create_model(tower_inputs, global_step, is_training_var)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/monitors/action_monitor.py", line 47, in _create_model
    use_nesterov=self._params.use_nesterov, norm_kernels=self._params.norm_kernels)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/actionnet.py", line 58, in __init__
    global_step, name, use_nesterov, norm_kernels)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/ssd.py", line 76, in __init__
    self._build_losses(labels, annot, backbone_name)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/actionnet.py", line 521, in _build_losses
    self._multibox_loss(labels, annot, class_agnostic=True, output_original_labels=True)
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/ssd.py", line 529, in _multibox_loss
    valid_gt_ids, valid_matched_scores, 1e-7, self._mbox_param['comp_loss_max_num_samples'], 'det_top')
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/ssd.py", line 295, in _get_top_matched_mask
    lambda: (tf.zeros_like(gt_ids, dtype=tf.bool), tf.ones_like(gt_ids, dtype=tf.float32)))
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2086, in cond
    orig_res_t, res_t = context_t.BuildCondBranch(true_fn)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1930, in BuildCondBranch
    original_result = fn()
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/ssd.py", line 294, in <lambda>
    lambda: _process(),
  File "/home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/ssd.py", line 271, in _process
    tf.reshape(grouped_matched_scores, dense_shape), k=num_samples_per_gt, sorted=False)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 2359, in top_k
    return gen_nn_ops.top_kv2(input, k=k, sorted=sorted, name=name)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 7701, in top_kv2
    "TopKV2", input=input, k=k, sorted=sorted, name=name)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/test/anaconda3/envs/tensorflow2.7/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): input must have at least k columns. Had 3, needed 5
	 [[node tower_0/ActionNet_losses/multibox_loss/det_top/cond/TopKV2 (defined at /home/test/song/training_extensions/misc/tensorflow_toolkit/action_detection/action_detection/nn/models/ssd.py:271)  = TopKV2[T=DT_FLOAT, sorted=false, _device="/job:localhost/replica:0/task:0/device:GPU:0"](tower_0/ActionNet_losses/multibox_loss/det_top_1/cond/Reshape, tower_0/ActionNet_losses/multibox_loss/det_top/cond/Maximum)]]
	 [[{{node tower_0/ActionNet_losses/multibox_loss/det_top/cond/ones/_4231}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_5426_tower_0/ActionNet_losses/multibox_loss/det_top/cond/ones", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

2021-10-21 09:33:36.070554: W tensorflow/core/kernels/data/generator_dataset_op.cc:78] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}} = PyFunc[Tin=[DT_INT64], Tout=[DT_INT64], token="pyfunc_2"](arg0)]]

Process finished with exit code 1

**Comment by morkovka1337** [comment]
It is hard to say. The code is old enough (it uses python2), and it is not maintained by us for a long time. Maybe there always such situation with batch size 1, but we just did not do such experiments, because, I have wrote earlier, people usually do not train models with batch size one. With batch size 1 loss usually is too noisy.
